### ISSUE TITLE
Download the balanced audioset issue

### ISSUE THREAD

**Issue by SteveTanggithub** [RicherMans/SAT#1]
I have downloaded the parallel and yt-dlp, but i sitll cannot download the dataset by running the .sh file. Would u help about this?
There are some screenshots about the parallel an yt-dlp folders and the error.
![image](https://github.com/RicherMans/SAT/assets/62332133/33b38d2c-1c8f-4715-b2e9-8a4fec8af054)

![image](https://github.com/RicherMans/SAT/assets/62332133/629ca313-285c-4430-bc30-fd9d460a164a)

![image](https://github.com/RicherMans/SAT/assets/62332133/855464e3-95bc-4546-96d7-cf524461b6e9)

**Comment by RicherMans** [comment]
Hey,
You need some proxy in order to access YouTube. The proxy can then be used with tools like [proxychains](https://github.com/haad/proxychains) .

**Comment by SteveTanggithub** [comment]
i am downloading the dataset now, and it comes out so many errors like below, is it normal?

ERROR: [youtube] XYPJ9VI3B4Q: Video unavailable
WARNING: [youtube] XWVGQbfpA0k: Signature extraction failed: Some formats may be missing
ERROR: [youtube] XZX89FQUOXQ: Video unavailable. This video contains content from Paramount Global (PMN), who has blocked it in your country on copyright grounds
ERROR: [youtube] XbqcSSoRhk0: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] XcGHrUDT8P8: Video unavailable
ERROR: [youtube] Xcxa3iDFvno: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] XkExQOFQCM8: Video unavailable
ERROR: [youtube] Xm9tBd0MLtE: Private video. Sign in if you've been granted access to this video
WARNING: [youtube] Failed to download MPD manifest: Remote end closed connection without response
ERROR: [youtube] XoQEJvNdO0c: Video unavailable
ERROR: [youtube] XqJXjpvJTzA: Video unavailable
ERROR: [youtube] Xpw3etLGLIY: Video unavailable
ERROR: [youtube] Xqn5dl27WY0: Video unavailable
ERROR: [youtube] XrLmM8bZTZA: Video unavailable. This video is no longer available because the uploader has closed their YouTube account.
ERROR: [youtube] XvMzLnl9wk8: Video unavailable
ERROR: [youtube] XwhstLcLfn8: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] Xy8fR4pJNmo: Video unavailable
ERROR: [youtube] Y-gkPWlrVYw: Video unavailable
ERROR: [youtube] Y23XRUQeDuI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] Y4TEp8xLTUM: Video unavailable
ERROR: [youtube] Y5VOsLeh4m4: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] Y7A_l2g2QzI: Video unavailable
ERROR: [youtube] Y7RRpZxa788: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] YCIQHsVCPWo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] YClFceJYHvk: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YEaVU-9ocKo: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YEdnv2gZBhM: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] YEpjvq6S68w: Video unavailable
ERROR: [youtube] YFHqHSc9AXU: Video unavailable
ERROR: [youtube] YJuXeTc2Fsw: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YKjkaPNJOXk: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YLMV2r2ZQeM: Video unavailable
ERROR: [youtube] YMG0foV0ZYk: Video unavailable
ERROR: [youtube] YNvlbMtntto: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YQNZDhQUTOM: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YR-T5pH2qLg: Video unavailable
ERROR: [youtube] YTapjEIgzkI: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] YX94Twfsi78: Video unavailable
ERROR: [youtube] YXRX1kVK5UI: Video unavailable
ERROR: [youtube] YY5CtRUyI_4: Video unavailable

**Comment by RicherMans** [comment]
Hey there,
yes, it is standard behaviour, since the original audioset cannot be "completely" downloaded.
The main reason for this is that many videos were deleted or were removed due to some issues with the content.

There has been a recent [paper](https://ieeexplore.ieee.org/abstract/document/10095255) from google, which shows that from the original ~2.1 Million Videos, one can currently only download ~1.7 Million samples. 
This number is likely to further decrease.

For the balanced audioset subset, I commonly can download ~ 15000 samples from the original 21000.

Kind regards,
Heinrich Dinkel
