### ISSUE TITLE
ERROR: Could not consume arg: config/sat/balanced_sat_2_2s.yaml Usage: 2_train_sat.py - <command>   available commands:    train  For detailed information on this command, run:   2_train_sat.py - --help

### ISSUE THREAD

**Issue by herbiel** [RicherMans/SAT#5]
![image](https://github.com/user-attachments/assets/2eac6b86-a2c0-4df8-bebf-1197dad535c1)
![image](https://github.com/user-attachments/assets/8fc23fe8-6fdd-4461-9d27-796e7f186232)
报错了

**Comment by RicherMans** [comment]
显示: available commands: train

```
python3 2_train_sat.py train config/sat/balanced.yaml
```

**Comment by herbiel** [comment]
Downloading ./data/csvs//balanced_train_segments.csv Subset using 64 workers
parallel: invalid option -- '-'
Downloading ./data/csvs//eval_segments.csv Subset using 64 workers
parallel: invalid option -- '-'
Finished Downloading data

**Comment by RicherMans** [comment]
可能parallel 版本太低？

**Comment by herbiel** [comment]
![image](https://github.com/user-attachments/assets/36f058c7-1752-4387-ac07-3490ec0172f5)
还是有问题诶parallel已经更新了

**Comment by RicherMans** [comment]
下载数据一般要最近的yt-dlp。

**Comment by herbiel** [comment]
![image](https://github.com/user-attachments/assets/6c82f7b8-4c57-4031-89e1-6eb1a489703b)
弄自己的数据训练 这个labels有影响吗

**Comment by RicherMans** [comment]
你就用自己的标签和数据
